### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by giampaolo** [openlabs/magento#23]
This is currently missing. Any plan to migrate magento to Python 3? 

```
$ pip3.4 install magento --user
Downloading/unpacking magento
  Using download cache from /home/giampaolo/.pip/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fm%2Fmagento%2Fmagento-0.4.tar.gz
  Running setup.py (path:/tmp/pip_build_giampaolo/magento/setup.py) egg_info for package magento
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_giampaolo/magento/setup.py", line 14, in <module>
        execfile(os.path.join('magento', 'version.py'))
    NameError: name 'execfile' is not defined
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_giampaolo/magento/setup.py", line 14, in <module>

    execfile(os.path.join('magento', 'version.py'))

NameError: name 'execfile' is not defined

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_giampaolo/magento
Storing debug log for failure in /home/giampaolo/.pip/pip.log
```
##

**Comment by tomaszsmolarek** [comment]
This patch seems to work perfectly. Any chance we could get this added to the repo? I'd like to be able to create a submodule out of your repo.

**Comment by sharoonthomas** [comment]
Can you send a patch to https://github.com/fulfilio/python-magento ? not maintained here anymore.
